### PR TITLE
feat: Forbid write access to root filesystem

### PR DESCRIPTION
**Pull request by lvyanru8200**
set vmalert container SecurityContext the value of ReadOnlyRootFilesystem is set to true

fix: https://github.com/VictoriaMetrics/operator/issues/637

### CODE REVIEW

**Comment by lvyanru8200** [comment]
cc @f41gh7

**Comment by lvyanru8200** [comment]
Should I make changes to the individual components of VictoriaMetrics as one pr or multiple

**Comment by Haleygo** [comment]
> Should I make changes to the individual components of VictoriaMetrics as one pr or multiple

I think it's ok to add them all in this pr.

**Comment by f41gh7** [comment]
I think, it's better to make this behavior configurable:
1) global setting, that enables security context for all components (non-root user, read-only root fs). With `BaseOperatorConfig.enableStrictSecurity`
2) new setting must respect user define configuration ( if read-only root fs disabled for some reason).

Something like:

```go
func addStrictSecuritySettingsToPod(p *v1.PodSpec, c *config.BaseOperatorConfig){
    /// fast path, disabled configuration or user controls it
    if !c.enableStrictSecurity || p.SecurityContext != nil{
          return 
   }
   // apply global security context
   // like FSGuuiD
   p.SecurityContext = &corev1.PodSecurityContext{
            RunAsNonRoot: true,
            RunAsUser: some_global_var,
            RunAsGroup: some_global_var,
            FSGroup: some_global_var,
   }
   for idx := range p.Containers {
       container := &p.Containers[idx]
       container.SecurityContext = &corev1.SecurityContext{
              ReadOnlyRootFilesystem: True,
      }
   }
}

```

**Comment by Amper** [comment]
Hey @lvyanru8200, thank you very much for your contribution.
We have not received any responses to comments and have decided to finalize your work in a [separate PR](https://github.com/VictoriaMetrics/operator/pull/692). This PR will be closed.

**Pull request closed without merging**
