### PR TITLE
Adding Name field to VMUser

### LINKED ISSUE #472: Name field in VMUserSpec
The name field passed for each user to vmauth is used in the label `username` for metrics `vmauth_user_requests_total` which will be useful to identify the source of the requests.

The documentation of victoriametrics states as below.
`vmauth` exports `vmauth_user_requests_total` metric with `username` label. The `username` label value equals to `username` field value set in the `-auth.config` file. It is possible to override or hide the value in the label by specifying `name` field. For example, the following config will result in `vmauth_user_requests_total{username="foobar"}` instead of `vmauth_user_requests_total{username="secret_user"}`

### PR DESCRIPTION
**Pull request by pavan541cs**
This PR is to fix #472

### CODE REVIEW

**Comment by pavan541cs** [comment]
@f41gh7 Please review this PR and comment on the same.

**Review by f41gh7 — APPROVED** [review]
LGTM

**Comment by f41gh7** [comment]
Thanks for contribution!

**Comment by pavan541cs** [comment]
What is the plan for the next release? Any tentative dates?

**Pull request merged**
