### PR TITLE
In PrometheusConverter in created objects include ownerReferences

### PR DESCRIPTION
**Pull request by teqwve**
I've noticed that removing a `PrometheusRule` doesn't make the corresponding `VMRule` deleted immediately as I've expected. As it seemed easy to code (just adding some `ownerReferences`) I've decided to have some fun and add it myself. For consistency I've updated other converters as well. Apart from e2e tests I've deployed it on some 'real' cluster and tested PrometheusRule behaviour - worked as expected.

During tests I've encountered that issue (at least I think it's an issue) with typo in prober discovery so I've fixed it as well.

Can such a feature be added? I haven't found any related information in documentation or discussion in issues (although I haven't searched a lot).

I'm not sure if this should be enabled by default. From my point of view it should, but I imagine it might break someone else's deployment (someone might, even unintentionally, rely on the fact that converted objects persist after original ones are removed). I can add some `EnablePrometheusConverterOwnerReferences` (false by default) setting to the configuration and pass it down to converters.

### CODE REVIEW

**Review by f41gh7 — CHANGES_REQUESTED** [review]
Thanks for submitting PR and spotting a typo with converter. 

  It looks good to me. Tests become nicer.

 There is an issue with objects update process. When operator starts, it updates all converted objects, but not all fields are copied from "old" objects. OwnerReferences are missing. It should be placed at:
https://github.com/VictoriaMetrics/operator/blob/master/controllers/vmprometheusconverter_controller.go#L248
https://github.com/VictoriaMetrics/operator/blob/master/controllers/vmprometheusconverter_controller.go#L299
https://github.com/VictoriaMetrics/operator/blob/master/controllers/vmprometheusconverter_controller.go#L349
https://github.com/VictoriaMetrics/operator/blob/master/controllers/vmprometheusconverter_controller.go#L444

with something like: 
```
existingVMProbe.OwnerReferences = vmProbe.OwnerReferences
```

> I'm not sure if this should be enabled by default. From my point of view it should, but I imagine it might break someone else's deployment (someone might, even unintentionally, rely on the fact that converted objects persist after original ones are removed). I can add some `EnablePrometheusConverterOwnerReferences` (false by default) setting to the configuration and pass it down to converters.

 I think that `EnablePrometheusConverterOwnerReferences` with default false - best solution for this problem. Can you add it? 
 Original intention was to provide simple and safe way for migration from one operator to another.

**Comment by teqwve** [comment]
Thanks for the reply!

> There is an issue with objects update process. When operator starts, it updates all converted objects, but not all fields are copied from "old" objects. OwnerReferences are missing. It should be placed at:
> https://github.com/VictoriaMetrics/operator/blob/master/controllers/vmprometheusconverter_controller.go#L248
> https://github.com/VictoriaMetrics/operator/blob/master/controllers/vmprometheusconverter_controller.go#L299
> https://github.com/VictoriaMetrics/operator/blob/master/controllers/vmprometheusconverter_controller.go#L349
> https://github.com/VictoriaMetrics/operator/blob/master/controllers/vmprometheusconverter_controller.go#L444
> 
> with something like:
> 
> ```
> existingVMProbe.OwnerReferences = vmProbe.OwnerReferences
> ```

Sorry, I should have read the code more carefully. I've fixed it and tested manually that redeploying the operator with changed setting updates every rule converted before (and generally that updates actually update OwnerReferences).

I've decided to not add tests for this (redeploying with different settings) because it would require me to restart manager during tests, reset it's configuration after tests and so on... I could just change the global config (since it's the same process and there are pointers everywhere), but it would make e2e tests quite tightly coupled with the actual implementation.

> > I'm not sure if this should be enabled by default. From my point of view it should, but I imagine it might break someone else's deployment (someone might, even unintentionally, rely on the fact that converted objects persist after original ones are removed). I can add some `EnablePrometheusConverterOwnerReferences` (false by default) setting to the configuration and pass it down to converters.
> 
> I think that `EnablePrometheusConverterOwnerReferences` with default false - best solution for this problem. Can you add it?
> Original intention was to provide simple and safe way for migration from one operator to another.

Added.

**Comment by teqwve** [comment]
The build is failing because it's a PR from a fork and github hides secrets :/

I don't know if you want to handle this somewhow, but maybe adding something like:
```
      - name: build crosscompile and push to remote registry
        env:
          TAG:   ${{ env.GITHUB_REF_SLUG }}
        run: |
          if [ -n '${{secrets.REPO_KEY}}' ]; then
            echo ${{secrets.REPO_KEY}} | docker login --username ${{secrets.REPO_USER}} --password-stdin
            make publish-via-docker
          else
            make build-operator-crosscompile docker-operator-crosscompile  # Just test if docker can be built
          fi
``` 
would make some sense?

**Review by f41gh7 — APPROVED** [review]
LGTM

**Comment by f41gh7** [comment]
Thanks for contribution!

**Comment by f41gh7** [comment]
> The build is failing because it's a PR from a fork and github hides secrets :/
> 
> I don't know if it's an issue for you, or if you want to handle this somewhow, but maybe adding something like:
> 
> ```
>       - name: build crosscompile and push to remote registry
>         env:
>           TAG:   ${{ env.GITHUB_REF_SLUG }}
>         run: |
>           if [ -n '${{secrets.REPO_KEY}}' ]; then
>             echo ${{secrets.REPO_KEY}} | docker login --username ${{secrets.REPO_USER}} --password-stdin
>             make publish-via-docker
>           else
>             make build-operator-crosscompile docker-operator-crosscompile  # Just test if docker can be built
>           fi
> ```
> 
> would make some sense?

 Yes, it makes sense. I'll fix lit a bit later.

**Comment by teqwve** [comment]
@f41gh7 thanks for devoting your time to this PR and generally thanks for you work!

**Pull request merged**
