### PR TITLE
Add a easy way to create simple topologySpreadConstraints and PodDisruptionBudget

### PR DESCRIPTION
**Pull request by umezawatakeshi**
implements #191 

Signed-off-by: UMEZAWA Takeshi <umezawa@utsoft.org>

### CODE REVIEW

**Review by f41gh7 — APPROVED** [review]
LGTM

**Comment by f41gh7** [comment]
Thanks for contribution!

**Comment by umezawatakeshi** [comment]
By the way, there is much duplicate code not only in this PR but also in the originally existing code. I think it is bug-prone and should be solved. However, I'm not sure that it should be done **now** because it could lead to a breaking change in Golang-level API, depending on how to solve it.

**Comment by f41gh7** [comment]
> By the way, there is much duplicate code not only in this PR but also in the originally existing code. I think it is bug-prone and should be solved. However, I'm not sure that it should be done **now** because it could lead to a breaking change in Golang-level API, depending on how to solve it.

 Yep, i've refactored it a bit.  For now, i prefer to make small patches with improvements - remove duplicate code and unify some parts.

  All breaking changes can be done before v1.0 release, if its needed.

**Pull request merged**
