### PR TITLE
supported multiple `if` conditions for relabeling(#730)

### PR DESCRIPTION
**Pull request by Amper**
issue #730

### CODE REVIEW

**Comment by Amper** [comment]
Hey @Haleygo and @f41gh7, I decided to make the `if` and `match` schemaless fields to support `string or array of strings` and avoid breaking backward compatibility, wdyt about it?

**Comment by f41gh7** [comment]
> Hey @Haleygo and @f41gh7, I decided to make the `if` and `match` schemaless fields to support `string or array of strings` and avoid breaking backward compatibility, wdyt about it?

Is it possible to apply those changes over exist operator installation?

**Comment by Amper** [comment]
> Is it possible to apply those changes over exist operator installation?

Yes, it works, I tested it - current values are saved.
The only problem with this approach is that, without webhooks enabled, any object of the wrong type can be mapped into this field and will be deployed - it will break only in the operator's log

**Review by f41gh7 — APPROVED** [review]
LGTM

**Pull request merged**
